apps:

# Scrapper
 - name: scrapper
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/binance.fastapi
   replicas: 1
   volumes:
     - name: cache
       mountPath: /var/cache/scrapper
       hostPath: /var/cache/scrapper
   secrets:
     - binance
   configmaps:
     - binance
     - questdb

# Plotter
 - name: plotter
   dev: true
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/seaborn.fastapi
   replicas: 1
   configmaps:
     - questdb
     
# Dataset
 - name: dataset
   dev: true
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/talib.fastapi
   replicas: 1
   configmaps:
     - questdb