apps:

# Scrapper
 - name: scrapper
   dev: True
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/fastapi.tb:latest
   replicas: 1
   volumes:
     - name: cache
       mountPath: /var/cache/scrapper
       hostPath: /var/cache/tb/scrapper
   secrets:
     - binance
   configmaps:
     - binance
     - questdb

# Plotter
 - name: plotter
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/fastapi.tb:latest
   replicas: 1
   configmaps:
     - questdb
     - dataset
     - mongodb
     - model

# Trainer
 - name: trainer
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/fastapi.tb:latest
   replicas: 1
   volumes:
     - name: cache
       mountPath: /var/cache/trainer
       hostPath: /var/cache/tb/trainer
     - name: models
       mountPath: /var/cache/models
       hostPath: /var/cache/tb/models
   configmaps:
     - questdb
     - dataset
     - mongodb
     - model

# Trader
 - name: trader
   dev: true
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/fastapi.tb:latest
   replicas: 1
   volumes:
     - name: cache
       mountPath: /var/cache/trader
       hostPath: /var/cache/tb/trader
     - name: models
       mountPath: /var/cache/models
       hostPath: /var/cache/tb/models
   secrets:
     - binance
   configmaps:
     - binance
     - questdb
     - dataset
     - mongodb
     - model
     
