tbmodsPath: /var/code/tb/tbmods

apps:

# Scrapper
 - name: scrapper
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/binance.fastapi
   replicas: 1
   volumes:
     - name: code
       mountPath: /code
       hostPath: /var/code/tb/apps/
   secrets:
     - binance
   configmaps:
     - binance
     - questdb
