apps:

# Scrapper
 - name: scrapper
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/binance.fastapi:latest
   replicas: 1
   volumes:
     - name: cache
       mountPath: /var/cache/scrapper
       hostPath: /var/cache/tb/scrapper
   secrets:
     - binance
   configmaps:
     - binance
     - questdb

# Plotter
 - name: plotter
   dev: true
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/seaborn.sklearn:latest
   replicas: 1
   configmaps:
     - questdb
     - dataset

# Trainer
 - name: trainer
   dev: true
   image: registry.devops.svc.k8s.slav.rocks:5000/tb/sklearn.talib:latest
   replicas: 1
   configmaps:
     - questdb
     - dataset
