clusterDomain: k8s.slav.rocks
nameOverride: front
image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.21.6-debian-10-r23
containerPorts:
  http: 8080
serverBlock: |-
  server {
    listen 0.0.0.0:{{ .Values.containerPorts.http }};
    add_header Last-Modified $date_gmt;
    add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    if_modified_since off;
    expires off;
    etag off;
    location /api/scrapper {
      rewrite /api/scrapper/(.*) /$1 break;
      proxy_pass http://scrapper.tb.svc.k8s.slav.rocks;
    }
    location /api/plotter {
      rewrite /api/plotter/(.*) /$1 break;
      proxy_pass http://plotter.tb.svc.k8s.slav.rocks;
    }
    location /api/dataset {
      rewrite /api/dataset/(.*) /$1 break;
      proxy_pass http://dataset.tb.svc.k8s.slav.rocks;
    }
  }
service:
  type: ClusterIP
  port: 80
  targetPort:
    http: http
extraVolumeMounts:
  - name: app
    mountPath: /app
    readOnly: true
extraVolumes:
  - name: app
    hostPath:
      path: /var/code/tb/apps/front/
