replicaCount: 1

image:
  repo: "telegraf"
  tag: "1.21-alpine"
  pullPolicy: IfNotPresent

env:
  - name: HOSTNAME
    value: "telegraf-scrapper"

service:
  enabled: false
  type: ClusterIP
  annotations: {}

config:
  agent:
    interval: "1s"
    flush_interval: "1s"
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_jitter: "0s"
    precision: ""
    debug: false
    quiet: false
    logfile: ""
    hostname: "$HOSTNAME"
    omit_hostname: false
  outputs:
    - file:
        files:
          - /dev/null
  inputs:
    - http:
        urls:
          - "http://scrapper.tb.svc.k8s.slav.rocks/klines/scrap/BTCUSDT"
        timeout: "1s"
        data_format: "json_v2"
