apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  TB_CUSUM_PCT_THRESHOLD: "2"
  TB_PERIOD_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "1.9"
  TB_TBM_DOWN_THRESH: "1.3"
  TB_FEATURES: | 
    {
      "sources":{
          "qdb":[
            "open",
            "high",
            "low",
            "close",
            "volume"
          ],
          "talib":[
             "rsi",
             "macd",
             "macdhist",
             "macdsignal",
             "adx",
             "adxr",
             "apo",
             "aroonup",
             "aroondown",
             "aroonosc",
             "bop",
             "cci",
             "cmo",
             "dx",
             "mfi",
             "minusdi",
             "minusdm",
             "mom",
             "plusdi",
             "plusdm",
             "ppo",
             "roc",
             "slowk",
             "slowd",
             "fastk",
             "fastd",
             "fastkrsi",
             "fastdrsi",
             "trix",
             "ultosc",
             "willr",
             "ssa",
             "ssb",
             "tenkan",
             "kijun"
          ]
      }
    }