apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  # LABELS
  TB_CUSUM_PCT_THRESHOLD: "0.5"
  TB_PERIOD_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "0.9"
  TB_TBM_DOWN_THRESH: "0.8"
  # TECH
  TB_OHLC_FEATURES: |
    {
        "open": {
            "scaled": "False",
            "source": "ohlc"
        },
        "high": {
            "scaled": "False",
            "source": "ohlc"
        },
        "low": {
            "scaled": "False",
            "source": "ohlc"
        },
        "close": {
            "scaled": "False",
            "source": "ohlc"
        }
    }
  TB_TECH_FEATURES: |
    {
        "ad": {
            "scaled": "False",
            "source": "indicators"
        },
        "adosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "adx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "adxr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "apo": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "aroonup": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroondown": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroonosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "atr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "avgprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "bop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cci": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "cdl2crows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3blackcrows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3inside": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3linestrike": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3outside": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3starinsouth": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3whitesoldiers": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlabandonedbaby": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdladvanceblock": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlbelthold": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlbreakaway": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlclosingmarubozu": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlconcealbabywall": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlcounterattack": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldarkcloudcover": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldojistar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldragonflydoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlengulfing": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdleveningdojistar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdleveningstar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlgapsidesidewhite": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlgravestonedoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhammer": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhangingman": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlharami": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlharamicross": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhighwave": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhikkake": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhikkakemod": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhomingpigeon": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlidentical3crows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlinneck": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlinvertedhammer": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlkicking": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlkickingbylength": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlladderbottom": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdllongleggeddoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdllongline": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmarubozu": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmatchinglow": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmathold": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmorningstardojistar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmorningstar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlonneck": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlpiercing": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlrickshawman": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlrisefall3methods": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlseparatinglines": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlshootingstar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlshortline": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlspinningtop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlstalledpattern": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlsticksandwich": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdltakuri": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdltasukigap": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlthrusting": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdltristar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlunique3river": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlupsidegap2crows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlxsidegap3methods": {
            "scaled": "True",
            "source": "indicators"
        },
        "cmo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "dx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "fastk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastkrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "fastdrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "hcdcperiod":{
            "scaled": "True",
            "source": "indicators"
        },
        "hcdcphase":{
            "scaled": "True",
            "source": "indicators"
        },
        "htphasorin":{
            "scaled": "True",
            "source": "indicators"
        },
        "htphasorqua":{
            "scaled": "True",
            "source": "indicators"
        },
        "htsinesine":{
            "scaled": "True",
            "source": "indicators"
        },
        "htsinelead":{
            "scaled": "True",
            "source": "indicators"
        },
        "httrendmode":{
            "scaled": "True",
            "source": "indicators"
        },
        "ma": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "medprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "macd": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdhist": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdsignal": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "mfi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "mom": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "natr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "number_of_trades": {
            "scaled": "False",
            "source": "ohlc"
        },
        "obv": {
            "scaled": "False",
            "source": "indicators"
        },
        "plusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "plusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ppo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "roc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocp": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "slowk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "slowd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "taker_buy_base_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "taker_buy_quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "trange": {
            "scaled": "True",
            "source": "indicators"
        },
        "trix": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "typprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "ultosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "wclprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "willr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        }
    }
  TB_TECH_FEATURES_SELECTED: 'roc-4-8,roc-1-10,macdsignal-1-4.8,macdsignal-0-5.9,rocr-0-3,macdsignal-1-8.10,rocr-1-4,ma-4-17,low-13,high-4,fastk-0-7.9,roc-0-8,rocp-2-9,cmo-1-9,cmo-0-10,willr-0-4,fastk-0-3.2,cmo-0-19,close-7,open-6,fastd-1-7.3,macdsignal-0-9.10,macdsignal-0-6.7,low-6,ma-4-3,open-17,mfi-1-5,fastk-0-6.2,macdsignal-0-5.7,cmo-0-3,macdhist-0-7.9,macdhist-0-6.8,roc-10-15,rsi-0-6,ma-2-4,dx-1-9,fastdrsi-1-7.7.1,macdsignal-1-5.9,macdsignal-1-3.9,rocp-3-9,ma-3-12,open-5,trix-2-16,rsi-1-13,macdsignal-1-6.7,rocr-2-4,close-1,macdsignal-0-3.5,macdsignal-1-4.7,macdsignal-0-5.6,open-9,apo-0-5.4,rocp-1-6,macdsignal-0-5.4,mfi-0-5,aroonup-1-3,ma-0-11,open-10,cmo-0-18,macdsignal-1-7.9,roc-7-6,macdhist-0-4.6,macdhist-0-6.9,ma-0-12,macdsignal-0-4.6,macdsignal-1-3.4,willr-0-6,rsi-0-7,macdsignal-0-4.8,aroonup-0-3,rocr-2-5,low-0,minusdm-0-15,cci-0-9,macdhist-0-4.9,apo-1-5.4,aroondown-0-6,macdhist-0-15.7,rocp-0-6,macdsignal-1-5.4,close-10,cmo-0-5,macdhist-1-7.10,rocr-5-4,rocp-4-9,macdhist-1-4.7,rocr-18-5,willr-0-10,macdhist-0-6.7,macdhist-0-7.8,macdsignal-0-5.8,roc-1-8,macdsignal-2-4.8,cmo-0-17,ma-1-12,cci-0-16,high-7,roc-5-8,macdhist-1-4.8,open-0,macdsignal-2-3.9,fastk-0-14.7,low-3,macdsignal-1-5.7,macdhist-1-6.9,macdhist-0-8.10,rsi-0-13,willr-0-16,macdhist-1-7.8,cmo-0-4,bop-1,fastdrsi-0-7.7.1,rocp-0-5,low-1,rocr-1-12,trix-4-16,rocr-0-4,macdhist-0-9.2,rsi-0-5,high-1,rsi-0-16,cci-0-13,aroondown-1-6,rocp-0-9,willr-0-13,adx-0-15,ma-1-9,open-16,macdsignal-0-7.9,number_of_trades-1,dx-0-9,cmo-0-7,minusdm-1-15,macdhist-1-15.7,high-0,mom-1-12,ma-9-17,rocr-6-5,rocp-1-9,aroonosc-0-4,close-2,macd-0-5.5,low-5,ma-13-7,rsi-0-19,roc-0-10,trix-0-16,ma-7-17,adx-1-15,close-11,ma-1-11,rocr-4-4,open-4,number_of_trades-0,macd-1-15.6,rocp-6-7,open-7,willr-0-17,trix-1-16,macdsignal-2-5.7,minusdi-0-11,cmo-0-9,roc-2-8,aroonosc-1-4,trix-5-16,macd-0-6.7,adxr-0-5,fastkrsi-1-4.3.2,fastd-0-7.3,cci-1-5,open-1,bop-0,adxr-1-5,trix-3-16,macdsignal-2-7.9,cci-0-5,rocr-3-4,rsi-0-10,fastkrsi-0-4.3.2,close-0,minusdi-1-11,fastk-1-7.9,macdhist-1-4.9,low-2,mom-0-12,macd-0-15.6,low-4,close-5'
  TB_ICHIMOKU_FEATURES: |
    {
        "tenkan": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "kijun": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssa": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssb": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "laggingspan": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        }
    }
  TB_ICHIMOKU_FEATURES_SELECTED: 'tenkan-0-9,kijun-0-26,ssa-0-9.26,ssb-0-52.26,laggingspan-0-26'