apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  TB_TECH_DATA_PERIOD: '1h'
  TB_CUSUM_PCT_THRESHOLD: "0.5"
  TB_PERIOD_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "0.9"
  TB_TBM_DOWN_THRESH: "0.8"
  TB_TECH_GRID_SEARCH_LAG: "20"
  TB_TECH_FEATURES_SELECTED: 'cdl2crows-0,cdl3blackcrows-0,cdl3inside-0,cdl3linestrike-0,cdl3outside-0,cdl3starinsouth-0,cdl3whitesoldiers-0,cdlabandonedbaby-0,cdladvanceblock-0,cdlbelthold-0,cdlbreakaway-0,cdlclosingmarubozu-0,cdlconcealbabywall-0,cdldarkcloudcover-0,cdldoji-0,cdldojistar-0,cdldragonflydoji-0,cdlengulfing-0,cdleveningdojistar-0,cdleveningstar-0,cdlgapsidesidewhite-0,cdlgravestonedoji-0,cdlhammer-0,cdlhangingman-0,cdlharami-0,cdlharamicross-0,cdlhighwave-0,cdlhikkake-0,cdlhikkakemod-0,cdlhomingpigeon-0,cdlidentical3crows-0,cdlinneck-0,cdlinvertedhammer-0,cdlkicking-0,cdlkickingbylength-0,cdlladderbottom-0,cdllongleggeddoji-0,cdllongline-0,cdlmarubozu-0,cdlmatchinglow-0,cdlmathold-0,cdlmorningstardojistar-0,cdlmorningstar-0,cdlonneck-0,cdlpiercing-0,cdlrickshawman-0,cdlrisefall3methods-0,cdlseparatinglines-0,cdlshootingstar-0,cdlshortline-0,cdlspinningtop-0,cdlstalledpattern-0,cdlsticksandwich-0,cdltakuri-0,cdltasukigap-0,cdlthrusting-0,cdltristar-0,cdlunique3river-0,cdlupsidegap2crows-0,cdlxsidegap3methods-0,cdlcounterattack-0'
  TB_TECH_FEATURES: |
    {
        "ad": {
            "scaled": "False",
            "source": "indicators"
        },
        "adosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "adx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "adxr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "apo": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "aroonup": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroondown": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroonosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "atr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "avgprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "bop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cci": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "cdl2crows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3blackcrows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3inside": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3linestrike": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3outside": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3starinsouth": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3whitesoldiers": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlabandonedbaby": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdladvanceblock": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlbelthold": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlbreakaway": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlclosingmarubozu": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlconcealbabywall": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlcounterattack": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldarkcloudcover": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldojistar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldragonflydoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlengulfing": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdleveningdojistar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdleveningstar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlgapsidesidewhite": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlgravestonedoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhammer": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhangingman": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlharami": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlharamicross": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhighwave": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhikkake": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhikkakemod": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhomingpigeon": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlidentical3crows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlinneck": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlinvertedhammer": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlkicking": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlkickingbylength": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlladderbottom": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdllongleggeddoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdllongline": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmarubozu": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmatchinglow": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmathold": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmorningstardojistar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmorningstar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlonneck": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlpiercing": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlrickshawman": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlrisefall3methods": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlseparatinglines": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlshootingstar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlshortline": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlspinningtop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlstalledpattern": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlsticksandwich": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdltakuri": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdltasukigap": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlthrusting": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdltristar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlunique3river": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlupsidegap2crows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlxsidegap3methods": {
            "scaled": "True",
            "source": "indicators"
        },
        "close": {
            "scaled": "False",
            "source": "ohlc"
        },
        "cmo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "dx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "fastk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastkrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "fastdrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "hcdcperiod":{
            "scaled": "True",
            "source": "indicators"
        },
        "hcdcphase":{
            "scaled": "True",
            "source": "indicators"
        },
        "htphasorin":{
            "scaled": "True",
            "source": "indicators"
        },
        "htphasorqua":{
            "scaled": "True",
            "source": "indicators"
        },
        "htsinesine":{
            "scaled": "True",
            "source": "indicators"
        },
        "htsinelead":{
            "scaled": "True",
            "source": "indicators"
        },
        "httrendmode":{
            "scaled": "True",
            "source": "indicators"
        },
        "high": {
            "scaled": "False",
            "source": "ohlc"
        },
        "kijun": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "low": {
            "scaled": "False",
            "source": "ohlc"
        },
        "ma": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "medprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "macd": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdhist": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdsignal": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "mfi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "mom": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "natr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "number_of_trades": {
            "scaled": "False",
            "source": "ohlc"
        },
        "open": {
            "scaled": "False",
            "source": "ohlc"
        },
        "obv": {
            "scaled": "False",
            "source": "indicators"
        },
        "plusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "plusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ppo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "roc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocp": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssa": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssb": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "slowk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "slowd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "taker_buy_base_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "taker_buy_quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "tenkan": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "trange": {
            "scaled": "True",
            "source": "indicators"
        },
        "trix": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "typprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "ultosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "wclprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "willr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        }
    }