apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  TB_TECH_DATA_START: '08-18-2017'
  TB_TECH_DATA_PERIOD: '1h'
  TB_CUSUM_PCT_THRESHOLD: "0.5"
  TB_PERIOD_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "0.9"
  TB_TBM_DOWN_THRESH: "0.8"
  TB_TECH_GRID_SEARCH_LAG: "20"
  TB_TECH_FEATURES_SELECTED: 'ma-0-3,cci-0-4,aroondown-0-5,macdsignal-1-9.10,kijun-1-19,apo-11-5.9,macd-1-18.5,macdhist-1-3.4,macdhist-0-5.7,trix-2-17,ppo-5-3.2,macdhist-1-5.7,ma-9-4,willr-0-7,ma-7-3,fastk-0-3.4,fastd-0-18.6,trix-4-17,rocr-7-6,volume-0,cmo-1-3,rocr-0-3,roc-1-15,ppo-1-3.2,fastk-0-7.9,volume-2,apo-0-13.9,roc-5-11,close-6,macdsignal-1-3.8,ppo-1-8.2,rocr-9-15,fastkrsi-1-11.6.5,trix-1-18,willr-0-17,roc-0-8,trix-5-17,low-4,rsi-0-3,ppo-10-19.8,high-6,low-1,ma-3-10,macdhist-0-6.7,adxr-0-18,fastd-1-18.6,roc-1-12,macdhist-0-7.9,minusdi-0-9,macdsignal-1-3.5,ppo-6-3.2,rocp-0-7,rocr-4-3,rocr-3-3,fastdrsi-1-11.3.4,willr-0-16,low-2,roc-4-11,roc-2-8,ppo-2-8.2,ma-6-10,fastk-0-6.3,trix-2-18,aroonup-1-4,macdhist-0-3.4,rsi-0-14,rocp-0-9,ma-2-15,macdsignal-2-9.10,volume-1,rsi-0-8,cci-1-19,close-4,cci-0-15,trix-1-17,adx-1-11,cci-0-19,high-0,macdsignal-1-4.8,macdsignal-0-3.5,open-1,ppo-3-6.4,ma-1-15,close-5,cci-0-12,close-8,macdsignal-1-11.4,open-5,trix-0-18,macdhist-1-3.7,rocp-0-4,trix-3-17,roc-1-8,macdsignal-0-3.8,ppo-1-19.8,ppo-11-19.8,ma-0-4,aroonup-0-4,macdhist-0-5.9,kijun-0-19,bop-1,low-5,minusdm-0-13,rsi-0-11,mfi-1-3,macd-1-4.9,fastk-0-8.5,cmo-0-5,ppo-0-19.8,low-0,open-3,roc-2-15,macd-0-18.5,cmo-0-13,open-7,cmo-0-11,ma-6-3,trix-0-17,fastdrsi-0-11.3.4,ma-1-13,rocp-1-9,macdsignal-0-5.9,adxr-1-18,cmo-0-6,rocp-1-7,ma-4-3,aroonosc-1-18,cci-0-8,mom-1-15,ssa-1-13,macdsignal-0-11.4,rsi-0-4,low-3,aroonosc-0-18,roc-6-11,mfi-0-3,adx-0-11,trix-6-17,rocp-2-7,close-2,fastd-0-4.2,ma-0-10,cmo-0-3,rsi-0-12,open-4,macdhist-1-7.9,macdsignal-0-9.10,cmo-0-19,close-7,roc-2-16,willr-0-3,macdhist-1-8.9,open-0,rocr-6-3,rocp-3-7,dx-1-13,high-1,cmo-0-16,fastkrsi-0-11.6.5,open-6,willr-0-8,cmo-0-4,close-0,fastk-0-3.6,ma-8-3,fastk-1-6.9,rocp-6-7,macdhist-1-6.7,cmo-2-16,ma-0-13,dx-0-13,fastk-0-6.9,rocr-8-6,macdhist-0-5.6,rsi-0-7,ssa-6-4,rocp-6-9,ssa-5-4,apo-1-13.9,low-6,minusdi-1-9,macdsignal-0-4.8,aroondown-1-5,roc-0-15,close-1,mom-1-6,cmo-0-7,bop-0,apo-3-5.9,open-2,macdhist-0-8.9,macdhist-1-5.6,ma-5-10'
  TB_TECH_FEATURES: |
    {
        "adx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "adxr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "apo": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "aroonup": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroondown": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroonosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "bop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cci": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "close": {
            "scaled": "False",
            "source": "ohlc"
        },
        "cmo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "dx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "fastk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastkrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "fastdrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "high": {
            "scaled": "False",
            "source": "ohlc"
        },
        "kijun": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "low": {
            "scaled": "False",
            "source": "ohlc"
        },
        "ma": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "macd": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdhist": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdsignal": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "mfi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "mom": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "number_of_trades": {
            "scaled": "False",
            "source": "ohlc"
        },
        "open": {
            "scaled": "False",
            "source": "ohlc"
        },
        "plusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "plusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ppo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "roc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocp": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssa": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssb": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "slowk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "slowd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "taker_buy_base_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "taker_buy_quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "tenkan": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "trix": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "ultosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "willr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        }
    }