apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  TB_TECH_DATA_START: '08-18-2017'
  TB_TECH_DATA_PERIOD: '1h'
  TB_CUSUM_PCT_THRESHOLD: "0.5"
  TB_PERIOD_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "0.9"
  TB_TBM_DOWN_THRESH: "0.8"
  TB_TECH_GRID_SEARCH_LAG: "20"
  TB_TECH_FEATURES_SELECTED: 'ma-8-15,cmo-0-11,macdsignal-0-5.8,apo-4-6.7,ppo-2-11.10,aroondown-5-19,macdsignal-1-6.9,dx-2-14,rocp-0-3,adxr-0-9,ppo-17-13.3,trix-16-10,aroondown-0-19,cmo-0-9,ma-1-10,willr-0-4,open-4,aroonosc-2-17,cmo-0-8,cmo-0-5,adx-0-11,macdsignal-0-4.9,aroonosc-1-17,adxr-1-9,macdsignal-1-4.9,macdsignal-0-7.9,close-11,macdhist-0-3.4,fastdrsi-3-6.3.4,ma-3-18,adx-3-11,close-0,macdhist-1-6.7,macdsignal-1-3.8,ma-0-3,apo-0-6.7,cmo-0-4,roc-10-7,apo-3-6.7,aroonup-4-15,macdsignal-0-3.8,adxr-4-9,macdsignal-1-3.9,macdsignal-0-5.6,macdsignal-0-7.8,macdhist-1-6.8,rocp-3-10,cmo-0-12,ppo-0-11.10,cmo-1-16,aroondown-4-19,dx-4-14,fastd-3-9.7,fastd-4-9.7,roc-1-18,aroondown-1-19,cmo-0-19,rsi-2-18,aroondown-3-19,rocp-3-3,adx-1-11,bop-3,adx-2-11,cmo-5-19,low-9,rsi-0-6,roc-1-11,fastk-0-7.9,macdsignal-1-3.4,macdsignal-0-6.9,ma-2-14,cmo-0-15,ma-1-15,aroonup-2-15,willr-0-3,willr-0-6,cci-0-6,aroondown-2-19,ma-16-11,aroonup-0-15,aroonup-5-15,dx-3-14,macdhist-0-3.5,cmo-0-14,adx-5-11,aroonosc-4-17,macdhist-0-6.10,rocp-1-4,rsi-1-18,macdhist-0-6.9,open-7,macdsignal-1-4.8,rocr-1-9,aroonosc-5-17,macdsignal-0-4.8,dx-0-14,close-5,macdhist-1-3.6,adxr-5-9,rocr-0-3,open-6,roc-6-3,macdsignal-1-4.6,ppo-18-13.3,bop-2,roc-6-6,trix-18-10,cci-2-17,cci-0-17,rsi-0-13,trix-13-19,rsi-1-13,open-5,cci-5-17,macdhist-0-3.8,macdsignal-1-5.8,trix-2-13,rocr-1-8,rocr-7-4,cmo-0-16,cmo-1-19,fastdrsi-5-6.3.4,aroonup-1-15,roc-0-4,trix-2-19,macdsignal-1-7.10,ppo-12-13.3,fastd-5-9.7,aroonup-3-15,dx-1-14,ssa-16-3,rocp-5-4,aroonosc-3-17,ppo-1-11.10,cmo-0-17,macdhist-0-3.6,rsi-0-17,bop-0,fastk-1-7.9,rocp-13-4,trix-10-14,macdhist-0-6.8,fastd-0-9.7,close-4,low-0,apo-1-6.7,macdsignal-0-6.8,high-1,rocr-18-9,macdsignal-0-3.9,close-3,macdhist-1-5.7,fastdrsi-2-6.3.4,close-1,apo-2-6.7,rsi-0-5,adxr-3-9,macdsignal-1-7.8,adx-4-11,rsi-0-3,macdhist-0-5.10,apo-5-6.7,cmo-3-19,bop-1,cmo-4-19,roc-3-6,dx-5-14,rocr-1-19,fastk-2-7.9,bop-5,cmo-2-19,rsi-0-18,fastdrsi-0-6.3.4,rsi-3-18,ma-1-14,bop-4,macdhist-0-6.7,aroonosc-0-17,cci-3-17,cci-1-17,fastdrsi-1-6.3.4,rocp-4-3,ppo-3-11.10,cmo-0-3,fastdrsi-4-6.3.4,fastd-2-9.7,macdsignal-2-3.9,macdsignal-1-6.8,adxr-2-9,fastd-1-9.7,macdsignal-0-4.6,cci-4-17,close-2'
  TB_TECH_FEATURES: |
    {
        "adx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "adxr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "apo": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "aroonup": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroondown": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroonosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "bop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cci": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "close": {
            "scaled": "False",
            "source": "ohlc"
        },
        "cmo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "dx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "fastk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastkrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "fastdrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "high": {
            "scaled": "False",
            "source": "ohlc"
        },
        "kijun": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "low": {
            "scaled": "False",
            "source": "ohlc"
        },
        "ma": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "macd": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdhist": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdsignal": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "mfi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "mom": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "open": {
            "scaled": "False",
            "source": "ohlc"
        },
        "plusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "plusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ppo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "roc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocp": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssa": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssb": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "slowk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "slowd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "tenkan": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "trix": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "ultosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "willr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        }
    }