apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  TB_CUSUM_PCT_THRESHOLD: "0.5"
  TB_PERIOD_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "0.9"
  TB_TBM_DOWN_THRESH: "0.8"
  TB_TECH_GRID_SEARCH_LAG: "20"
  TB_TECH_FEATURES_SELECTED: 'adx-0,adxr-0,apo-0,aroonup-0,aroondown-0,aroonosc-0,bop-0,cci-0,close-0,cmo-0,dx-0,fastk-0,fastd-0,fastkrsi-0,fastdrsi-0,high-0,kijun-0,low-0,ma-0,macd-0,macdhist-0,macdsignal-0,mfi-0,minusdi-0,minusdm-0,mom-0,open-0,plusdi-0,plusdm-0,ppo-0,roc-0,rocp-0,rocr-0,rsi-0,ssa-0,ssb-0,slowk-0,slowd-0,tenkan-0,trix-0,ultosc-0,volume-0,willr-0'
  TB_TECH_CLF_CONFIG: |
    {
        "n_estimators":"300",
        "oob_score":"True",
        "n_jobs":"-1",
        "verbose":"1",
        "class_weight":"balanced",
        "random_state":"42"
    }
  TB_TECH_FEATURES: |
    {
        "adx": {
            "scaled": "True",
            "source": "indicators"
        },
        "adxr": {
            "scaled": "True",
            "source": "indicators"
        },
        "apo": {
            "scaled": "False",
            "source": "indicators"
        },
        "aroonup": {
            "scaled": "True",
            "source": "indicators"
        },
        "aroondown": {
            "scaled": "True",
            "source": "indicators"
        },
        "aroonosc": {
            "scaled": "True",
            "source": "indicators"
        },
        "bop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cci": {
            "scaled": "True",
            "source": "indicators"
        },
        "close": {
            "scaled": "False",
            "source": "ohlc"
        },
        "cmo": {
            "scaled": "True",
            "source": "indicators"
        },
        "dx": {
            "scaled": "True",
            "source": "indicators"
        },
        "fastk": {
            "scaled": "True",
            "source": "indicators"
        },
        "fastd": {
            "scaled": "True",
            "source": "indicators"
        },
        "fastkrsi": {
            "scaled": "True",
            "source": "indicators"
        },
        "fastdrsi": {
            "scaled": "True",
            "source": "indicators"
        },
        "high": {
            "scaled": "False",
            "source": "ohlc"
        },
        "kijun": {
            "scaled": "False",
            "source": "indicators"
        },
        "low": {
            "scaled": "False",
            "source": "ohlc"
        },
        "ma": {
            "scaled": "False",
            "source": "indicators"
        },
        "macd": {
            "scaled": "False",
            "source": "indicators"
        },
        "macdhist": {
            "scaled": "False",
            "source": "indicators"
        },
        "macdsignal": {
            "scaled": "False",
            "source": "indicators"
        },
        "mfi": {
            "scaled": "True",
            "source": "indicators"
        },
        "minusdi": {
            "scaled": "True",
            "source": "indicators"
        },
        "minusdm": {
            "scaled": "False",
            "source": "indicators"
        },
        "mom": {
            "scaled": "False",
            "source": "indicators"
        },
        "open": {
            "scaled": "False",
            "source": "ohlc"
        },
        "plusdi": {
            "scaled": "True",
            "source": "indicators"
        },
        "plusdm": {
            "scaled": "False",
            "source": "indicators"
        },
        "ppo": {
            "scaled": "True",
            "source": "indicators"
        },
        "roc": {
            "scaled": "True",
            "source": "indicators"
        },
        "rocp": {
            "scaled": "True",
            "source": "indicators"
        },
        "rocr": {
            "scaled": "True",
            "source": "indicators"
        },
        "rsi": {
            "scaled": "True",
            "source": "indicators"
        },
        "ssa": {
            "scaled": "False",
            "source": "indicators"
        },
        "ssb": {
            "scaled": "False",
            "source": "indicators"
        },
        "slowk": {
            "scaled": "True",
            "source": "indicators"
        },
        "slowd": {
            "scaled": "True",
            "source": "indicators"
        },
        "tenkan": {
            "scaled": "False",
            "source": "indicators"
        },
        "trix": {
            "scaled": "True",
            "source": "indicators"
        },
        "ultosc": {
            "scaled": "True",
            "source": "indicators"
        },
        "volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "willr": {
            "scaled": "True",
            "source": "indicators"
        }
    }