apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  # LABELS
  TB_CUSUM_PCT_THRESHOLD: "0.5"
  TB_PERIOD_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "0.9"
  TB_TBM_DOWN_THRESH: "0.8"
  # TECH
  TB_OHLC_FEATURES: |
    {
        "open": {
            "scaled": "False",
            "source": "ohlc"
        },
        "high": {
            "scaled": "False",
            "source": "ohlc"
        },
        "low": {
            "scaled": "False",
            "source": "ohlc"
        },
        "close": {
            "scaled": "False",
            "source": "ohlc"
        }
    }
  TB_TECH_FEATURES: |
    {
        "ad": {
            "scaled": "False",
            "source": "indicators"
        },
        "adosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "adx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "adxr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "apo": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "aroonup": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroondown": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroonosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "atr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "avgprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "bop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cci": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "cdl2crows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3blackcrows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3inside": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3linestrike": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3outside": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3starinsouth": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdl3whitesoldiers": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlabandonedbaby": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdladvanceblock": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlbelthold": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlbreakaway": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlclosingmarubozu": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlconcealbabywall": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlcounterattack": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldarkcloudcover": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldojistar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdldragonflydoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlengulfing": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdleveningdojistar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdleveningstar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlgapsidesidewhite": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlgravestonedoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhammer": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhangingman": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlharami": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlharamicross": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhighwave": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhikkake": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhikkakemod": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlhomingpigeon": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlidentical3crows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlinneck": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlinvertedhammer": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlkicking": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlkickingbylength": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlladderbottom": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdllongleggeddoji": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdllongline": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmarubozu": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmatchinglow": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmathold": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmorningstardojistar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlmorningstar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlonneck": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlpiercing": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlrickshawman": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlrisefall3methods": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlseparatinglines": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlshootingstar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlshortline": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlspinningtop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlstalledpattern": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlsticksandwich": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdltakuri": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdltasukigap": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlthrusting": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdltristar": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlunique3river": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlupsidegap2crows": {
            "scaled": "True",
            "source": "indicators"
        },
        "cdlxsidegap3methods": {
            "scaled": "True",
            "source": "indicators"
        },
        "cmo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "dx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "fastk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastkrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "fastdrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "hcdcperiod":{
            "scaled": "True",
            "source": "indicators"
        },
        "hcdcphase":{
            "scaled": "True",
            "source": "indicators"
        },
        "htphasorin":{
            "scaled": "True",
            "source": "indicators"
        },
        "htphasorqua":{
            "scaled": "True",
            "source": "indicators"
        },
        "htsinesine":{
            "scaled": "True",
            "source": "indicators"
        },
        "htsinelead":{
            "scaled": "True",
            "source": "indicators"
        },
        "httrendmode":{
            "scaled": "True",
            "source": "indicators"
        },
        "ma": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "medprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "macd": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdhist": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdsignal": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "mfi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "mom": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "natr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "number_of_trades": {
            "scaled": "False",
            "source": "ohlc"
        },
        "obv": {
            "scaled": "False",
            "source": "indicators"
        },
        "plusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "plusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ppo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "roc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocp": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "slowk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "slowd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "taker_buy_base_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "taker_buy_quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "trange": {
            "scaled": "True",
            "source": "indicators"
        },
        "trix": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "typprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "ultosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "wclprice": {
            "scaled": "False",
            "source": "indicators"
        },
        "willr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        }
    }
  TB_TECH_FEATURES_SELECTED: 'ad-0,adosc-0-2.4'
  TB_ICHIMOKU_FEATURES: |
    {
        "tenkan": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "kijun": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssa": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "ssb": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "laggingspan": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        }
    }
  TB_ICHIMOKU_FEATURES_SELECTED: 'tenkan-0-9,kijun-0-26,ssa-0-9.26,ssb-0-52.26,laggingspan-0-26'