apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  TB_TECH_DATA_START: '08-18-2017'
  TB_TECH_DATA_PERIOD: '1h'
  TB_CUSUM_PCT_THRESHOLD: "0.5"
  TB_PERIOD_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "0.9"
  TB_TBM_DOWN_THRESH: "0.8"
  TB_TECH_GRID_SEARCH_LAG: "20"
  TB_TECH_FEATURES_SELECTED: 'cmo-0-6,roc-0-4,fastk-0-19.9,willr-0-5,ma-0-3,aroonosc-11-15,rocr-0-8,open-4,fastk-0-4.5,macdhist-0-8.10,adxr-10-13,cmo-2-13,adx-5-4,aroonosc-4-15,rsi-0-5,adx-6-4,fastk-0-3.9,roc-0-6,adxr-13-13,roc-7-4,adxr-8-13,open-0,apo-2-3.8,aroondown-1-13,roc-5-17,aroonup-1-15,macdsignal-1-6.10,ma-1-9,adx-10-4,roc-0-3,close-6,ppo-6-16.10,rsi-0-8,macdsignal-0-4.5,rocr-1-9,aroondown-11-13,close-0,open-6,low-0,adxr-1-13,macdhist-0-5.8,roc-5-4,macdsignal-0-3.8,macdhist-0-6.7,macdsignal-0-3.9,rsi-0-6,adx-12-4,rocr-5-19,fastk-0-3.3,rocp-13-3,adxr-5-13,adxr-14-13,roc-1-4,aroonosc-13-15,macdhist-0-4.7,macdsignal-0-8.9,macdhist-0-3.7,ppo-9-19.2,macdhist-1-4.5,apo-10-3.8,aroondown-6-13,macdsignal-1-3.8,adx-1-4,low-9,adxr-4-13,macdhist-1-5.9,macdsignal-1-8.9,ppo-8-19.2,aroonosc-6-15,macdsignal-0-6.10,macdsignal-1-4.5,roc-1-16,macdhist-1-3.7,rocp-4-9,macdhist-1-8.10,volume-0,adx-2-4,aroonosc-1-15,cmo-0-10,aroonup-12-15,rsi-0-17,apo-1-3.8,aroondown-7-13,macdhist-0-3.6,macdsignal-0-5.6,macdsignal-0-7.8,ppo-11-19.2,ppo-0-18.9,ppo-5-17.6,rocp-1-3,fastk-0-4.7,roc-3-4,ma-0-7,adxr-12-13,ppo-5-18.9,ppo-10-19.2,willr-0-6,aroonosc-10-15,aroonup-10-15,adx-9-4,cmo-0-14,ppo-2-18.9,rocp-4-3,aroonup-0-15,macdhist-0-5.7,ppo-3-17.6,apo-3-3.8,cmo-0-3,ppo-13-17.6,macdsignal-2-3.9,rocp-1-9,apo-7-3.8,adx-11-4,macdhist-0-4.5,ma-0-5,roc-4-3,rocr-0-3,macdsignal-1-3.9,apo-11-3.8,adx-4-4,aroondown-3-13,macdsignal-0-6.7,adxr-9-13,roc-9-4,aroonup-11-15,cci-0-7,adxr-3-13,adx-8-4,adxr-6-13,fastk-0-7.8,apo-4-3.8,cmo-0-5,aroonosc-3-15,ppo-4-18.9,macdsignal-1-5.6,ppo-0-18.6,rocp-0-4,aroonosc-0-15,cmo-0-13,aroonosc-14-15,apo-9-3.8,apo-5-3.8,aroondown-4-13,macdsignal-1-7.9,apo-12-3.8,cmo-0-16,macdhist-0-8.9,high-0,macdhist-0-6.9,willr-0-4,close-1,rocr-2-15,roc-0-17,aroonosc-12-15,adx-0-4,macdhist-0-5.9,adxr-0-13,apo-6-3.8,macdhist-1-6.9,apo-0-3.8,ma-4-9,macdhist-1-5.7,cmo-0-8,open-1,aroondown-5-13,apo-8-3.8,open-9,cci-0-5,adx-13-4,aroonosc-2-15,aroonosc-7-15,aroondown-0-13,aroondown-9-13,adx-7-4,aroondown-12-13,macdsignal-1-6.7,roc-4-12,macdhist-1-5.8,apo-14-3.8,aroondown-8-13,apo-13-3.8,rocr-4-9,aroonosc-9-15,aroondown-14-13,bop-0,roc-0-5,aroonup-13-15,aroonosc-8-15,rsi-0-12,adx-3-4,adxr-11-13,aroonosc-5-15,adx-14-4,aroondown-2-13,adxr-2-13,aroondown-10-13,rocp-0-3,cmo-0-4,aroondown-13-13,adxr-7-13'
  TB_TECH_FEATURES: |
    {
        "adx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "adxr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "apo": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "aroonup": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroondown": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroonosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "bop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cci": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "close": {
            "scaled": "False",
            "source": "ohlc"
        },
        "cmo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "dx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "fastk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastkrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "fastdrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "high": {
            "scaled": "False",
            "source": "ohlc"
        },
        "kijun": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "low": {
            "scaled": "False",
            "source": "ohlc"
        },
        "ma": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "macd": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdhist": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdsignal": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "mfi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "mom": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "open": {
            "scaled": "False",
            "source": "ohlc"
        },
        "plusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "plusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ppo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "roc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocp": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssa": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssb": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "slowk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "slowd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "tenkan": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "trix": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "ultosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "willr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        }
    }