apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  TB_TECH_DATA_PERIOD: '1h'
  TB_CUSUM_PCT_THRESHOLD: "0.5"
  TB_PERIOD_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "0.9"
  TB_TBM_DOWN_THRESH: "0.8"
  TB_TECH_GRID_SEARCH_LAG: "20"
  TB_TECH_FEATURES_SELECTED: 'macdsignal-0-5.9,tenkan-0-3,rocr-1-5,aroondown-4-19,cmo-0-10,apo-9-10.6,ma-2-7,aroonosc-6-3,roc-2-3,apo-6-10.6,minusdi-0-18,apo-11-10.6,rocr-0-5,cmo-0-3,macdsignal-0-5.7,number_of_trades-0,adxr-17-8,aroondown-8-19,aroonosc-13-3,apo-1-10.6,adx-2-7,rocp-2-8,macdsignal-1-5.9,macdsignal-1-3.9,adx-11-7,adx-0-7,aroonosc-0-3,close-1,macdhist-0-8.9,macdsignal-0-3.5,apo-0-3.7,aroondown-6-19,ppo-2-8.2,minusdi-1-18,adxr-6-8,aroonosc-11-3,aroonosc-7-3,adx-12-7,adxr-16-8,plusdi-2-14,aroonosc-10-3,trix-2-14,apo-0-10.6,aroondown-14-19,ma-1-7,apo-7-10.6,aroondown-11-19,rocp-1-8,apo-17-10.6,macdsignal-1-4.10,macdsignal-1-7.9,adxr-7-8,macdhist-0-4.6,aroondown-3-19,aroondown-7-19,apo-1-3.7,aroondown-16-19,ma-0-7,macdhist-0-6.9,adx-17-7,trix-0-14,adx-1-7,adxr-3-8,aroondown-10-19,rocr-2-5,low-0,macdhist-0-4.9,apo-10-10.6,mom-1-13,cmo-0-5,ppo-1-8.2,high-2,adxr-8-8,plusdi-0-14,aroonosc-12-3,apo-15-10.6,mfi-1-12,dx-0-3,macdhist-0-7.8,adx-8-7,aroondown-9-19,slowd-2-17.5,ultosc-1-15.7,aroonosc-15-3,open-0,ssa-2-19,rsi-1-12,adxr-9-8,macdsignal-1-5.7,adx-7-7,aroonosc-5-3,adx-16-7,adx-5-7,macdhist-2-9.3,adxr-5-8,ultosc-0-15.7,slowd-0-17.5,cmo-0-4,low-1,ssa-0-19,rocp-0-8,aroonosc-17-3,high-1,cci-0-13,aroonosc-16-3,number_of_trades-2,macdsignal-0-4.10,trix-1-14,apo-5-10.6,aroondown-2-19,aroonosc-4-3,macdsignal-2-3.5,macdhist-0-3.9,mfi-0-12,macdsignal-0-7.9,willr-0-19,apo-4-10.6,aroonosc-14-3,apo-16-10.6,aroondown-12-19,aroondown-5-19,high-0,ultosc-2-15.7,macdhist-0-9.3,adxr-12-8,willr-1-19,roc-0-3,adxr-11-8,apo-14-10.6,macdsignal-1-4.9,close-2,taker_buy_base_asset_volume-0,macdhist-0-5.8,open-2,mom-2-13,macdsignal-1-4.5,macdhist-1-8.9,aroondown-0-19,ssa-1-19,apo-13-10.6,macdsignal-0-4.7,adxr-15-8,adxr-4-8,adx-14-7,adxr-13-8,adx-4-7,aroondown-15-19,rsi-0-12,mfi-2-12,apo-2-10.6,apo-8-10.6,tenkan-2-3,mom-0-13,macdhist-0-3.10,fastd-0-3.5,slowd-1-17.5,adx-13-7,adxr-10-8,cmo-1-5,macdhist-0-4.7,adx-6-7,apo-3-10.6,taker_buy_quote_asset_volume-1,ppo-0-8.2,cmo-0-6,bop-2,adx-10-7,roc-1-3,adx-15-7,adxr-1-8,apo-2-3.7,open-1,bop-0,fastk-0-5.5,macd-0-6.3,adx-3-7,aroondown-17-19,macdhist-0-3.5,tenkan-1-3,cmo-0-13,dx-2-3,adxr-0-8,close-0,aroonosc-1-3,adx-9-7,rsi-0-14,minusdi-2-18,aroondown-1-19,rsi-2-12,aroonosc-2-3,adxr-2-8,low-2,aroonosc-3-3,apo-12-10.6,macdsignal-1-3.5,macdsignal-0-4.9,adxr-14-8,aroondown-13-19,aroonosc-8-3,fastd-2-3.5'
  TB_TECH_FEATURES: |
    {
        "adx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "adxr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "apo": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "aroonup": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroondown": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "aroonosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "bop": {
            "scaled": "True",
            "source": "indicators"
        },
        "cci": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "close": {
            "scaled": "False",
            "source": "ohlc"
        },
        "cmo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "dx": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "fastk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "fastkrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "fastdrsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "3"
        },
        "high": {
            "scaled": "False",
            "source": "ohlc"
        },
        "kijun": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "low": {
            "scaled": "False",
            "source": "ohlc"
        },
        "ma": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "macd": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdhist": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "macdsignal": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "2"
        },
        "mfi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "minusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "mom": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "number_of_trades": {
            "scaled": "False",
            "source": "ohlc"
        },
        "open": {
            "scaled": "False",
            "source": "ohlc"
        },
        "plusdi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "plusdm": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ppo": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "roc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocp": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rocr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "rsi": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssa": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "ssb": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "slowk": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "slowd": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "taker_buy_base_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "taker_buy_quote_asset_volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "tenkan": {
            "scaled": "False",
            "source": "indicators",
            "nb_args": "1"
        },
        "trix": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        },
        "ultosc": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "2"
        },
        "volume": {
            "scaled": "False",
            "source": "ohlc"
        },
        "willr": {
            "scaled": "True",
            "source": "indicators",
            "nb_args": "1"
        }
    }