apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset
data:
  TB_CUSUM_PCT_THRESHOLD: "2"
  TB_DAILY_VOL_SPAN: "26"
  TB_TBM_UP_THRESH: "1"
  TB_TBM_DOWN_THRESH: "0.5"
  TB_TBM_MIN_RET: "0.03"
  TB_FEATURES: | 
    {
      "sources":{
          "qdb":[
            "open",
            "high",
            "low",
            "close",
            "volume"
          ],
          "talib":[
             "rsi"
          ]
      }
    }