{{- range $.Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap." $.Release.Name ".yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .name }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: TB_APP
              value: {{ .name }}
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}
          image: {{ .image }}
          command: ["uvicorn"]
          args: ["$(TB_APP).main:app","--host","0.0.0.0","--port","80"{{ if .dev }},"--reload",{{ end }}] 
          volumeMounts:
          {{- range .volumes }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
          {{- end }}
          - name: tbmods
            mountPath: /usr/local/lib/python3.9/tbmods
      volumes:
      {{- range .volumes }}
      - name: {{ .name }}
        hostPath:
          path: {{ .hostPath }}
      {{- end }}
      - name: tbmods
        hostPath:
          path: {{ $.Values.tbmodsPath }}
{{- end }}
